name: Flow
on: [push]

env:
  PREFECT_KEY: ${{ secrets.PREFECT_KEY }}
  PREFECT_NAME: ${{ secrets.PREFECT_NAME }}
  PROJECT_ID: ${{ secrets.PROJECT_ID }}
  PROJECT_REGION: ${{ secrets.PROJECT_REGION }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        run: pip install pipenv && pipenv install

      - name: Login prefect
        run: pipenv run prefect cloud login --key ${{ env.PREFECT_KEY }} --workspace ${{ env.PREFECT_NAME }}

      - name: Run flow
        run: pipenv run python flow.py --project_id=${{ env.PROJECT_ID }} --region=${{ env.PROJECT_REGION }}
