name: Flow
on:
  push:
    branches:
      - '*'


env:
  PREFECT_ID: ${{env.PREFECT_ID}}
  PREFECT_NAME: ${{env.PREFECT_NAME}}
  PROJECT_ID: ${{env.PROJECT_ID}}
  PROJECT_REGION: ${{env.PROJECT_REGION}}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9

      - name: Install dependencies
        working-directory: "./*"
        run: pip install pipenv && pipenv install

      - name: Login prefect
        working-directory: "./*"
        run: prefect cloud login --key ${{env.PROJECT_ID}} --workspace ${{env.PREFECT_NAME}}

      - name: Run flow
        working-directory: "./*"
        run: pipenv run python flow.py --project_id=${{env.PROJECT_ID}} --region=${{env.PROJECT_REGION}}
